before:
  hooks:
    - rice embed-go

builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - windows

release:
  github:
    owner: niranjan94
    name: vault-front

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
