language: go

go:
- "1.x"

before_install:
  - nvm install 10
  - nvm use 10
  - make deps

env:
  - GO111MODULE=on

script:
- bash scripts/test.sh ci_mode
- make build
- git reset --hard HEAD

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
